const topics = [
  { id: 1,  category: "financial", answer: "IAS 16",              clue: "Property, Plant & Equipment" },
  { id: 2,  category: "financial", answer: "IFRS 15",             clue: "Revenue from Contracts" },
  { id: 3,  category: "financial", answer: "Break Even Point",    clue: "No Profit No Loss" },
  { id: 4,  category: "financial", answer: "Depreciation",        clue: "Reduction in Asset Value" },
  { id: 5,  category: "financial", answer: "Goodwill",            clue: "Intangible on Acquisition" },
  { id: 6,  category: "financial", answer: "IFRS 16",             clue: "Lease Accounting" },
  { id: 7,  category: "financial", answer: "IAS 36",              clue: "Impairment of Assets" },
  { id: 8,  category: "financial", answer: "Accruals",            clue: "Expense Incurred Not Yet Paid" },
  { id: 9,  category: "financial", answer: "Prepayments",         clue: "Paid in Advance" },
  { id: 10, category: "financial", answer: "IAS 37",              clue: "Provisions and Contingencies" },
  { id: 11, category: "financial", answer: "IFRS 9",              clue: "Financial Instruments" },
  { id: 12, category: "financial", answer: "IAS 2",               clue: "Valuation of Inventories" },
  { id: 13, category: "financial", answer: "Marginal Costing",    clue: "Variable Cost Only" },
  { id: 14, category: "financial", answer: "Absorption Costing",  clue: "Fixed Cost Included in Product" },
  { id: 15, category: "financial", answer: "IAS 12",              clue: "Income Taxes" },
  { id: 16, category: "financial", answer: "IFRS 3",              clue: "Business Combinations" },
  { id: 17, category: "financial", answer: "IAS 38",              clue: "Intangible Assets" },
  { id: 18, category: "financial", answer: "Variance Analysis",   clue: "Actual vs Budget Difference" },
  { id: 19, category: "financial", answer: "Working Capital",     clue: "Current Assets minus Current Liabilities" },
  { id: 20, category: "financial", answer: "IFRS 13",             clue: "Fair Value Measurement" },
  { id: 21, category: "financial", answer: "IAS 10",              clue: "Events After Reporting Period" },
  { id: 22, category: "financial", answer: "Contribution Margin", clue: "Sales minus Variable Costs" },
  { id: 23, category: "financial", answer: "IAS 7",               clue: "Cash Flow Statement" },
  { id: 24, category: "financial", answer: "IAS 1",               clue: "Presentation of Financial Statements" },
  { id: 25, category: "financial", answer: "Deferred Tax",        clue: "Timing Difference in Tax" },
  { id: 26, category: "financial", answer: "IAS 21",              clue: "Effects of Foreign Exchange Rates" },
  { id: 27, category: "financial", answer: "Gearing Ratio",       clue: "Debt to Equity Proportion" },
  { id: 28, category: "financial", answer: "IFRS 10",             clue: "Consolidated Financial Statements" },
  { id: 29, category: "financial", answer: "IAS 19",              clue: "Employee Benefits" },
  { id: 30, category: "financial", answer: "Return on Capital",   clue: "Profit Earned on Investment" },

  // ─── BANK ─────────────────────────────────────────────────────────────────
  { id: 31, category: "bank", answer: "LIBOR",                clue: "Interbank Lending Rate" },
  { id: 32, category: "bank", answer: "Basel III",            clue: "Bank Capital Requirements" },
  { id: 33, category: "bank", answer: "Credit Risk",          clue: "Borrower May Default" },
  { id: 34, category: "bank", answer: "Liquidity Ratio",      clue: "Ability to Meet Short-Term Obligations" },
  { id: 35, category: "bank", answer: "Repo Rate",            clue: "Central Bank Lending Rate" },
  { id: 36, category: "bank", answer: "KYC",                  clue: "Know Your Customer" },
  { id: 37, category: "bank", answer: "Net Interest Margin",  clue: "Bank Profit on Loans vs Deposits" },
  { id: 38, category: "bank", answer: "Capital Adequacy",     clue: "Buffer Against Financial Losses" },
  { id: 39, category: "bank", answer: "Non-Performing Loan",  clue: "Overdue Loan Not Being Repaid" },
  { id: 40, category: "bank", answer: "Fractional Reserve",   clue: "Banks Lend More Than They Hold" },
  { id: 41, category: "bank", answer: "Overdraft",            clue: "Spend Beyond Account Balance" },
  { id: 42, category: "bank", answer: "Letter of Credit",     clue: "Bank Guarantee for Trade" },
  { id: 43, category: "bank", answer: "SWIFT",                clue: "International Payment Messaging" },
  { id: 44, category: "bank", answer: "Mortgage",             clue: "Loan Secured Against Property" },
  { id: 45, category: "bank", answer: "Collateral",           clue: "Asset Pledged for a Loan" },
  { id: 46, category: "bank", answer: "RTGS",                 clue: "Real Time Gross Settlement" },
  { id: 47, category: "bank", answer: "AML",                  clue: "Anti Money Laundering" },
  { id: 48, category: "bank", answer: "CRR",                  clue: "Cash Reserve Ratio" },
  { id: 49, category: "bank", answer: "SLR",                  clue: "Statutory Liquidity Ratio" },
  { id: 50, category: "bank", answer: "Hedging",              clue: "Reducing Financial Risk" },
  { id: 51, category: "bank", answer: "Prime Rate",           clue: "Best Rate Offered to Top Borrowers" },
  { id: 52, category: "bank", answer: "Debit Card",           clue: "Spends Directly from Your Account" },
  { id: 53, category: "bank", answer: "Fixed Deposit",        clue: "Locked Savings for Fixed Period" },
  { id: 54, category: "bank", answer: "Bank Reconciliation",  clue: "Match Cashbook with Bank Statement" },
  { id: 55, category: "bank", answer: "Credit Score",         clue: "Measure of Creditworthiness" },
  { id: 56, category: "bank", answer: "Forfeiting",           clue: "Buying Export Receivables at Discount" },
  { id: 57, category: "bank", answer: "Factoring",            clue: "Selling Receivables to a Third Party" },
  { id: 58, category: "bank", answer: "Revolving Credit",     clue: "Reusable Credit Facility" },
  { id: 60, category: "bank", answer: "Vostro Account",       clue: "Foreign Bank Account Held with Us" },

  // ─── GENERAL ──────────────────────────────────────────────────────────────
  { id: 61, category: "general", answer: "Inflation",          clue: "Rise in General Price Level" },
  { id: 62, category: "general", answer: "GDP",                clue: "Total Output of a Country" },
  { id: 63, category: "general", answer: "Opportunity Cost",   clue: "Value of Next Best Alternative" },
  { id: 64, category: "general", answer: "Supply Chain",       clue: "Flow from Producer to Consumer" },
  { id: 65, category: "general", answer: "Monopoly",           clue: "Single Seller in the Market" },
  { id: 66, category: "general", answer: "Elasticity",         clue: "Sensitivity of Demand to Price" },
  { id: 67, category: "general", answer: "Recession",          clue: "Two Consecutive Quarters of Decline" },
  { id: 68, category: "general", answer: "Fiscal Policy",      clue: "Government Spending and Taxation" },
  { id: 69, category: "general", answer: "Monetary Policy",    clue: "Central Bank Controls Money Supply" },
  { id: 70, category: "general", answer: "Trade Deficit",      clue: "Imports Exceed Exports" },
  { id: 71, category: "general", answer: "Outsourcing",        clue: "Hiring External Party for Tasks" },
  { id: 72, category: "general", answer: "Economies of Scale", clue: "Cost Falls as Output Rises" },
  { id: 73, category: "general", answer: "Market Saturation",  clue: "No Room for New Customers" },
  { id: 74, category: "general", answer: "Audit",              clue: "Independent Examination of Accounts" },
  { id: 75, category: "general", answer: "Dividend",           clue: "Share of Company Profit Paid Out" },
  { id: 76, category: "general", answer: "IPO",                clue: "Company Lists on Stock Exchange" },
  { id: 77, category: "general", answer: "Merger",             clue: "Two Companies Combine Into One" },
  { id: 78, category: "general", answer: "Acquisition",        clue: "One Company Buys Another" },
  { id: 79, category: "general", answer: "Stakeholder",        clue: "Anyone Affected by the Business" },
  { id: 80, category: "general", answer: "Cash Flow",          clue: "Movement of Money In and Out" },
  { id: 81, category: "general", answer: "Balance Sheet",      clue: "Snapshot of Assets and Liabilities" },
  { id: 82, category: "general", answer: "Income Statement",   clue: "Shows Profit or Loss for the Period" },
  { id: 83, category: "general", answer: "Equity",             clue: "Owner's Share in the Business" },
  { id: 84, category: "general", answer: "Liability",          clue: "What the Business Owes" },
  { id: 85, category: "general", answer: "Asset",              clue: "What the Business Owns" },
  { id: 86, category: "general", answer: "Budget",             clue: "Planned Income and Expenditure" },
  { id: 87, category: "general", answer: "Profit Margin",      clue: "Profit as Percentage of Sales" },
  { id: 88, category: "general", answer: "Benchmark",          clue: "Standard Used for Comparison" },
  { id: 89, category: "general", answer: "Turnover",           clue: "Total Revenue of a Business" },
  { id: 90, category: "general", answer: "Solvency",           clue: "Ability to Pay Long-Term Debts" },

  // ─── MOVIE ────────────────────────────────────────────────────────────────
  { id: 91, category: "movie", answer: "Inception",          clue: "Dreams within dreams heist" },
  { id: 92, category: "movie", answer: "Titanic",            clue: "Sinking ship tragic romance" },
  { id: 93, category: "movie", answer: "The Matrix",         clue: "Simulation, red pill and blue pill" },
  { id: 94, category: "movie", answer: "Avatar",             clue: "Blue alien Na'vi on Pandora" },
  { id: 95, category: "movie", answer: "The Godfather",      clue: "Mafia crime family empire" },
  { id: 96, category: "movie", answer: "Jurassic Park",      clue: "Cloned dinosaurs run wild" },
  { id: 97, category: "movie", answer: "Star Wars",          clue: "Space conflict with Jedi and Sith" },
  { id: 98, category: "movie", answer: "Harry Potter",       clue: "Young wizard boy defeats Voldemort" },
  { id: 100, category: "movie", answer: "Gladiator",         clue: "Roman general turned arena fighter" },
];

export default topics;